export const langs = {
  title: 'Панель управления',
  photos_list_title: 'Фотографии',
  upload_to_yandex_disk_button: 'Загрузить',
  go_to_yandex_disk_action: 'Перейти на Яндекс.Диск',
  placeholder_photos_list: 'Все фотографии из чата загружены на Яндекс.Диск',
  tags_list_title: 'Теги',
  yandex_disk_folder_link: 'https://disk.yandex.ru/client/disk/%D0%91%D1%83%D1%85%D0%B3%D0%B0%D0%BB%D1%82%D0%B5%D1%80%D0%B8%D1%8F',
  tag_label_title: 'Название',
  tag_label_folder: 'Папка',
  save_tag_button: 'Сохранить',
  delete_tag_button: 'Удалить',
  tag_placeholder_title: 'Введите название тега',
  tag_placeholder_folder: 'Введите название папки на Яндекс.Диске',
  cancel_button: 'Отмена',
  delete_tag_title: 'Удаление тега',
  select_tag_label: 'Тег для загрузки',
  select_tag_placeholder: 'Не выбран тег',
  delete_tag_confirm: 'Вы уверены, что хотите удалить тег "{tag_name}"?',
};
